name: Build Cocos Creator Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Install Cocos Creator CLI
      run: |
        npm install -g cocos-creator-cli
        cocos -v

    - name: Build Cocos Creator project
      run: |
        cocos build --platform web-mobile --build-path ./build

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: cocos-build
        path: ./build
