name: Build Cocos Creator Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Cocos Creator CLI
      run: |
        mkdir cocos
        cd cocos
        wget https://download.cocos.com/CocosCreator/v3.6.3/CocosCreator_v3.6.3_Installer.deb
        sudo dpkg -i CocosCreator_v3.6.3_Installer.deb
        sudo apt-get install -f

    - name: Build Cocos Creator project
      run: |
        /Applications/CocosCreator/Creator/3.6.3/CocosCreator --path . --build "platform=web-mobile"

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: cocos-build
        path: ./build
