name: Build Cocos Creator Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Install Cocos Creator CLI
      run: |
        mkdir -p ~/cocos
        cd ~/cocos
        wget -O cocos-cli.tar.gz https://github.com/cocos/cocos-engine/archive/refs/tags/3.8.4.tar.gz
        tar -xzf cocos-cli.tar.gz
        sudo mv cocos /usr/local/bin/cocos
        cocos -v

    - name: Build Cocos Creator project
      run: |
        cocos build --platform web-mobile --build-path ./build

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: cocos-build
        path: ./build
